//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFINAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Address { get; set; }
        public string Hobbies { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string UserImage { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        
        public Nullable<System.DateTime> Dob { get; set; }
    }
}
